// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpTmhPYD3LWTmp9EzA3q3I7SXvT6n73FE',
    appId: '1:525124221680:web:d56e5d49f586e6b116a035',
    messagingSenderId: '525124221680',
    projectId: 'school-flutter-project',
    authDomain: 'school-flutter-project.firebaseapp.com',
    storageBucket: 'school-flutter-project.appspot.com',
    measurementId: 'G-C6ESBP6BDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7259VuewJxRq_vKVf3ndOGWjdU6DEvbM',
    appId: '1:525124221680:android:bca516732213b88416a035',
    messagingSenderId: '525124221680',
    projectId: 'school-flutter-project',
    storageBucket: 'school-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATXnSVwu_tLnJuyeKOQ_B9B-LB55U2aFQ',
    appId: '1:525124221680:ios:aefbc0a5285a083f16a035',
    messagingSenderId: '525124221680',
    projectId: 'school-flutter-project',
    storageBucket: 'school-flutter-project.appspot.com',
    iosClientId: '525124221680-eushgnrus763dv12fgkn5t8fv5pbskmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolProject',
  );
}
